name: Go Project Build

run-name: hello world

on:
  push:
    branches:
      - main

jobs:
  build-all:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: CheckOut
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - run: go version

      - name: Build on linux
        env:
          GOOS: linux
          GOARCH: amd64      
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          cd hello
          go build -o main-linux .
          ls
      
      - name: Build on windows
        # env:
        #   GOOS: windows
        #   GOARCH: amd64
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          cd hello
          go build -o main-win.exe .
          ls
      
      - name: Build on macOS
        env:
          GOOS: darwin
          GOARCH: amd64 
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          cd hello
          go build -o main-darwin .
          ls