name: Hello World

run-name: hello-world

on:
  push:
    branches:
      - main

jobs:
  # 作业名
  build-go-project:
    # 选择运行器
    runs-on: macos-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - run: go version

      - name: Build
        run: |
          ls
          cd hello
          go run main.go
          go build -o hello main.go
      
      - name: Upload Build Project
        uses: actions/upload-artifact@v3
        with:
          name: hello
          path: hello/hello
      - run: pwd && ls

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: hello
          tag_name: ${{ github.ref }}
          body: This is the first release of my app.
      
      - name: Upload to Release
        uses: svenstaro/upload-release-action@2.4.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hello
          asset_name: hello_macOS
          tag: ${{ github.ref }}
          overwrite: true
          body: This is the first release