name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        go-version: [1.16.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build Application
        run: go build -o hello/hello hello/main.go

      - name: Zip Application
        uses: montudor/action-zip@v1.0.0
        with:
          args: -r -9 hello.zip hello/

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            This is an automated release for version v${{ github.run_number }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@2.4.1
        with:
          asset_path: ./hello.zip
          asset_name: hello-${{ matrix.os }}-${{ matrix.go-version }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
