name: Hello World

run-name: hello-world

on:
  push:
    branches:
      - main

jobs:
  # 作业名
  build-go-project:
    # 选择运行器
    runs-on: macos-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - run: go version

      - name: Build
        run: |
          ls
          cd hello
          go run main.go
          go build main.go